# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_python.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(538, 169)
        self.pushButton_giris = QtWidgets.QPushButton(Form)
        self.pushButton_giris.setGeometry(QtCore.QRect(430, 50, 93, 28))
        self.pushButton_giris.setObjectName("pushButton_giris")
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 50, 160, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_giris = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_giris.setObjectName("label_giris")
        self.verticalLayout.addWidget(self.label_giris)
        self.label_sifre = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_sifre.setObjectName("label_sifre")
        self.verticalLayout.addWidget(self.label_sifre)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(240, 50, 160, 80))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit_kullaniciadi = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_kullaniciadi.setObjectName("lineEdit_kullaniciadi")
        self.verticalLayout_2.addWidget(self.lineEdit_kullaniciadi)
        self.lineEdit_sifre = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_sifre.setObjectName("lineEdit_sifre")
        self.verticalLayout_2.addWidget(self.lineEdit_sifre)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_giris.setText(_translate("Form", "giris"))
        self.label_giris.setText(_translate("Form", "kullanıcı_adi"))
        self.label_sifre.setText(_translate("Form", "sifre"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
