# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'radio.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(807, 389)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_icecek = QtWidgets.QGroupBox(Form)
        self.groupBox_icecek.setObjectName("groupBox_icecek")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_icecek)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioButton_6 = QtWidgets.QRadioButton(self.groupBox_icecek)
        self.radioButton_6.setObjectName("radioButton_6")
        self.verticalLayout_2.addWidget(self.radioButton_6)
        self.radioButton_7 = QtWidgets.QRadioButton(self.groupBox_icecek)
        self.radioButton_7.setObjectName("radioButton_7")
        self.verticalLayout_2.addWidget(self.radioButton_7)
        self.radioButton_8 = QtWidgets.QRadioButton(self.groupBox_icecek)
        self.radioButton_8.setObjectName("radioButton_8")
        self.verticalLayout_2.addWidget(self.radioButton_8)
        self.radioButton_5 = QtWidgets.QRadioButton(self.groupBox_icecek)
        self.radioButton_5.setObjectName("radioButton_5")
        self.verticalLayout_2.addWidget(self.radioButton_5)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addWidget(self.groupBox_icecek)
        self.groupBox_menu = QtWidgets.QGroupBox(Form)
        self.groupBox_menu.setObjectName("groupBox_menu")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_menu)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_menu)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout.addWidget(self.radioButton)
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_menu)
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout.addWidget(self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox_menu)
        self.radioButton_4.setObjectName("radioButton_4")
        self.verticalLayout.addWidget(self.radioButton_4)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_menu)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout.addWidget(self.radioButton_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addWidget(self.groupBox_menu)
        self.pushButton_ode = QtWidgets.QPushButton(Form)
        self.pushButton_ode.setObjectName("pushButton_ode")
        self.verticalLayout_3.addWidget(self.pushButton_ode)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "radio kullanımı"))
        self.groupBox_icecek.setTitle(_translate("Form", "içecek"))
        self.radioButton_6.setText(_translate("Form", "acık cay"))
        self.radioButton_7.setText(_translate("Form", "demli çay"))
        self.radioButton_8.setText(_translate("Form", "tavşan kanı çay"))
        self.radioButton_5.setText(_translate("Form", "ayran"))
        self.groupBox_menu.setTitle(_translate("Form", "menü"))
        self.radioButton.setText(_translate("Form", "dawıx"))
        self.radioButton_3.setText(_translate("Form", "xoroz (hemide iri)"))
        self.radioButton_4.setText(_translate("Form", "döner ama dawıx"))
        self.radioButton_2.setText(_translate("Form", "iskender ama dawıx"))
        self.pushButton_ode.setText(_translate("Form", "ÖDE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
